const menuPlayers = [
  {
    name: "Lebron James",
    position: "POWER FORWARD (PF)",
    age: 38,
    height: 2.06,
    number: 23,
    point: 28.9,
    reb: 8.3,
    ast: 6.8,
    conference: "West",
    src: "./src/img/lebron.jpg",
  },
  {
    name: "Stephen Curry",
    position: "POINT GUARD (PG)",
    age: 35,
    height: 1.88,
    number: 30,
    point: 29.4,
    reb: 6.1,
    ast: 6.3,
    conference: "West",
    src: "./src/img/curry.jpg",
  },
  {
    name: "Kevin Durant",
    position: "POWER FORWARD (PF)",
    age: 35,
    height: 2.11,
    number: 35,
    point: 29.7,
    reb: 6.7,
    ast: 5.3,
    conference: "West",
    src: "./src/img/durant1.jpg",
  },
  {
    name: "Jayson Tatum",
    position: "SMALL FORWARD (SF)",
    age: 25,
    height: 2.03,
    number: 0,
    point: 30.1,
    reb: 8.8,
    ast: 4.6,
    conference: "East",
    src: "./src/img/tatum4.jpg",
  },
  {
    name: "Luka Dončić",
    position: "POINT GUARD (PG)",
    age: 24,
    height: 2.01,
    number: 77,
    point: 32.4,
    reb: 8.6,
    ast: 8.0,
    conference: "West",
    src: "./src/img/luka8.jpg",
  },
  {
    name: "Nikola Jokic",
    position: "CENTER (C)",
    age: 28,
    height: 2.11,
    number: 15,
    point: 24.5,
    reb: 11.8,
    ast: 9.8,
    conference: "West",
    src: "./src/img/nikola.jpg",
  },
  {
    name: "Joel Embiid",
    position: "CENTER (C)",
    age: 29,
    height: 2.13,
    number: 21,
    point: 33.1,
    reb: 10.2,
    ast: 4.2,
    conference: "East",
    src: "./src/img/embiid6.jpg",
  },
  {
    name: "Giannis Antetokounmpo",
    position: "POWER FORWARD (PF)",
    age: 29,
    height: 2.11,
    number: 34,
    point: 31.1,
    reb: 11.8,
    ast: 5.7,
    conference: "East",
    src: "./src/img/giannis1.jpg",
  },
];
